### ISSUE TITLE
Data source attribute does not consider empty snippet params prefix

### ISSUE THREAD

**Issue by pun-ky** [Knotx/knotx-data-bridge#35]
**Describe the bug**
Data bridge module does not support empty snippet params prefix.

**To Reproduce**
When considering stack config

```
global {
  snippetTagName = "knotx-snippet"
  snippetParamsPrefix = ""
}

config.splitter.options.config {
  snippetOptions {
    tagName = ${global.snippetTagName}
    paramsPrefix = ${global.snippetParamsPrefix} 
  }
}
```

This will cause:

```
2018-10-12 11:21:13.972 [vert.x-eventloop-thread-3] ERROR i.k.d.core.DataBridgeKnotProxy - Error happened during Template processing
java.lang.ArrayIndexOutOfBoundsException: 3
        at io.knotx.databridge.core.attribute.DataSourceAttribute.from(DataSourceAttribute.java:42)
        at io.knotx.databridge.core.impl.FragmentContext.lambda$from$1(FragmentContext.java:60)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.knotx.databridge.core.impl.FragmentContext.from(FragmentContext.java:59)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)

```

**Expected behavior**
It should be allowed to have empty snippet params prefix and working data bridge module.

**Comment by pun-ky** [comment]
because of custom tag usage, please ensure that extra attribute `style="display:none"` (which I am adding to ensure knotx powered markup be not rendered) will be supported / not cause any similar errors.

**Comment by tomaszmichalak** [comment]
Interesting, we found unit test that checks this case:
io.knotx.databridge.core.impl.FragmentContextTest#from_whenFragmentContainsServices_expectFragmentContextWithProperNumberOfServicesExtracted

The problem appeared in Gradle configuration:
https://github.com/Knotx/knotx-data-bridge/pull/32

This test fails so the bug is correct ;)
